import * as THREE from 'three';
import { createEnvironment } from '../world/Environment';
import { placement, createGhost } from '../building/Placement';
import { createTool } from '../items/Tools';

type Kind='tree'|'rock';
type Node={kind:Kind;mesh:THREE.Group;hp:number};
type Save={wood:number;stone:number;walls:{x:number;z:number;rot:number}[];foundations:{x:number;z:number}[]};
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<div id="hud"><div class="top"><div class="brand">ISLAND <span>//</span> SURVIVAL</div><div class="pill">ALPHA 0.3 · ОДИНОЧНЫЙ МИР</div></div><div class="help"><b>W A S D</b> — движение<br><b>Мышь</b> — осмотр<br><b>ЛКМ</b> — добывать ресурс<br><b>1</b> — топор · <b>2</b> — кирка<br><b>I</b> — инвентарь · <b>B</b> — стройка<br><b>E</b> — построить · <b>ESC</b> — курсор</div><div class="crosshair">+</div><div id="prompt" class="prompt">Найдите дерево или камень</div><div id="toast" class="toast"></div><div class="stats"><div class="stat"><small>ЗДОРОВЬЕ <span id="healthNum">100</span></small><div class="track"><div class="fill" style="width:100%"></div></div></div><div class="stat"><small>ВОДА <span id="waterNum">100</span></small><div class="track"><div id="waterBar" class="fill" style="width:100%"></div></div></div><div class="stat"><small>ЕДА <span id="foodNum">100</span></small><div class="track"><div id="foodBar" class="fill" style="width:100%"></div></div></div></div><div class="right"><div id="tool1" class="slot active">🪓<small>1 · ТОПОР</small></div><div id="tool2" class="slot">⛏️<small>2 · КИРКА</small></div><div id="buildSlot" class="slot">🏠<small>B · СТРОИТЬ</small></div></div><div id="panel" class="panel hidden"></div></div><div id="start"><div class="intro"><div class="brand">SURVIVAL SANDBOX · PROTOTYPE</div><h1>ISLAND</h1><p>Исследуйте остров. Рубите деревья, добывайте камень, стройте собственную базу. Ваш прогресс сохраняется в браузере.</p><button id="play" class="btn">НАЧАТЬ ВЫЖИВАНИЕ →</button><p style="font-size:12px">Для управления нужен компьютер с клавиатурой и мышью.</p></div></div>`;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x91c4d3);scene.fog=new THREE.FogExp2(0x91c4d3,.007);
const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.1,700);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;app.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe0f5ff,0x6e7958,2.2));const sun=new THREE.DirectionalLight(0xffe3af,2.5);sun.position.set(80,110,40);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-120;sun.shadow.camera.right=120;sun.shadow.camera.top=120;sun.shadow.camera.bottom=-120;scene.add(sun);
const mat=(c:number)=>new THREE.MeshStandardMaterial({color:c,roughness:.9});const grass=mat(0x668d54),sand=mat(0xd1bd86),wood=mat(0x73543a),leaf=mat(0x356d3e),rockmat=mat(0x828985),building=mat(0x977655);
let seed=112233;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
const environment=createEnvironment(scene,rand);
const player=new THREE.Group();scene.add(player);player.position.set(0,0,8);
const skin=mat(0xc99a73),cloth=mat(0x41594b),pants=mat(0x343c3d),leather=mat(0x655039),metal=mat(0x77838b);
function part(parent:THREE.Object3D,geo:THREE.BufferGeometry,m:THREE.Material,x:number,y:number,z:number){const mesh=new THREE.Mesh(geo,m);mesh.position.set(x,y,z);mesh.castShadow=true;parent.add(mesh);return mesh}
part(player,new THREE.CapsuleGeometry(.39,.58,6,12),cloth,0,1.48,0);
part(player,new THREE.SphereGeometry(.285,24,16),skin,0,2.27,0);
part(player,new THREE.SphereGeometry(.292,24,12,0,Math.PI*2,0,Math.PI*.42),mat(0x302b23),0,2.29,0);
part(player,new THREE.BoxGeometry(.74,.65,.26),leather,0,1.43,.37);
for(const x of [-.11,.11])part(player,new THREE.SphereGeometry(.025,8,6),mat(0x222222),x,2.29,-.263);
part(player,new THREE.BoxGeometry(.19,.08,.08),mat(0x735344),0,2.12,-.265);
const leftArm=new THREE.Group(),rightArm=new THREE.Group(),leftLeg=new THREE.Group(),rightLeg=new THREE.Group();
leftArm.position.set(-.52,1.86,0);rightArm.position.set(.52,1.86,0);leftLeg.position.set(-.23,1.02,0);rightLeg.position.set(.23,1.02,0);
for(const limb of [leftArm,rightArm,leftLeg,rightLeg])player.add(limb);
for(const arm of [leftArm,rightArm]){part(arm,new THREE.CapsuleGeometry(.135,.48,5,10),cloth,0,-.34,0);part(arm,new THREE.BoxGeometry(.24,.22,.26),skin,0,-.78,0)}
for(const leg of [leftLeg,rightLeg]){part(leg,new THREE.CapsuleGeometry(.15,.64,5,10),pants,0,-.43,0);part(leg,new THREE.BoxGeometry(.33,.18,.49),leather,0,-.89,-.08)}
const heldTool=new THREE.Group();rightArm.add(heldTool);heldTool.position.set(0,-.8,-.08);
const axe=createTool(heldTool,'axe');const pickaxe=createTool(heldTool,'pickaxe');
let swingTime=0,walkPhase=0,walkWeight=0;
function animateCharacter(dt:number,moving:boolean,running:boolean){walkWeight=THREE.MathUtils.damp(walkWeight,moving?1:0,9,dt);walkPhase+=dt*(running?12:8);const stride=Math.sin(walkPhase)*walkWeight*(running?.75:.52);leftLeg.rotation.x=stride;rightLeg.rotation.x=-stride;leftArm.rotation.x=-stride*.7;rightArm.rotation.x=stride*.7;player.position.y=0; if(swingTime>0){swingTime=Math.max(0,swingTime-dt);const t=1-swingTime/.48;rightArm.rotation.x=-.4-Math.sin(t*Math.PI)*1.65;rightArm.rotation.z=-.18; }else rightArm.rotation.z=0;axe.visible=tool===1;pickaxe.visible=tool===2}
const nodes:Node[]=[];
function tree(x:number,z:number){const g=new THREE.Group();const bark=mat(0x5c4433);const needles=mat(0x345b35);const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.19,.38,4.2,11),bark);trunk.position.y=2.1;trunk.castShadow=true;g.add(trunk);for(let i=0;i<5;i++){const crown=new THREE.Mesh(new THREE.ConeGeometry(2.1-i*.23,2.8,11),needles);crown.position.y=3.25+i*.75;crown.castShadow=true;g.add(crown)}g.scale.setScalar(.8+rand()*.55);g.rotation.y=rand()*6.28;g.position.set(x,0,z);scene.add(g);nodes.push({kind:'tree',mesh:g,hp:4})}
function rock(x:number,z:number){const g=new THREE.Group();for(let i=0;i<4;i++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.65+rand()*.5,1),rockmat);m.position.set((rand()-.5)*1.2,.45,(rand()-.5)*1.2);m.scale.y=.65;m.rotation.set(rand(),rand()*6,rand());m.castShadow=true;g.add(m)}g.position.set(x,0,z);scene.add(g);nodes.push({kind:'rock',mesh:g,hp:4})}
for(let i=0;i<100;i++){const x=(rand()-.5)*160,z=(rand()-.5)*160;if(Math.hypot(x,z)<17)continue;(rand()<.73?tree:rock)(x,z)}for(let i=0;i<12;i++){const a=i*2.4;tree(Math.cos(a)* (17+i*2),Math.sin(a)*(17+i*2))}for(let i=0;i<8;i++){const a=i*3.7;rock(Math.cos(a)* (13+i*3),Math.sin(a)*(13+i*3))}
const saved=(()=>{try{return JSON.parse(localStorage.getItem('island-save-v1')||'null') as Save|null}catch{return null}})();let resources={wood:saved?.wood??0,stone:saved?.stone??0};let foundations=saved?.foundations??[];let walls=saved?.walls??[];
function foundation(x:number,z:number){const m=new THREE.Mesh(new THREE.BoxGeometry(4,.32,4),building);m.position.set(x,.16,z);m.receiveShadow=true;m.castShadow=true;scene.add(m)}function wall(x:number,z:number,rot:number){const m=new THREE.Mesh(new THREE.BoxGeometry(4,3,.25),building);m.position.set(x,1.65,z);m.rotation.y=rot;m.castShadow=true;scene.add(m)}foundations.forEach(v=>foundation(v.x,v.z));walls.forEach(v=>wall(v.x,v.z,v.rot));
function save(){localStorage.setItem('island-save-v1',JSON.stringify({...resources,foundations,walls}))}let toastTimeout=0;function toast(msg:string){const el=document.querySelector<HTMLElement>('#toast')!;el.textContent=msg;el.classList.add('show');clearTimeout(toastTimeout);toastTimeout=window.setTimeout(()=>el.classList.remove('show'),2300)}
const ghost=createGhost(scene);
const panel=document.querySelector<HTMLElement>('#panel')!;let openPanel='' ;let tool=1;let buildMode=false;let buildType:'foundation'|'wall'='foundation';
type Item={id:string;label:string;icon:string;count:number};
const inventory:Item[]=[{id:'axe',label:'Топор',icon:'🪓',count:1},{id:'pickaxe',label:'Кирка',icon:'⛏️',count:1}];
function inventoryItems(){return [...inventory,{id:'wood',label:'Древесина',icon:'🪵',count:resources.wood},{id:'stone',label:'Камень',icon:'🪨',count:resources.stone}].filter(i=>i.count>0)}
let selectedSlot=0;
function renderPanel(){if(!openPanel){panel.classList.add('hidden');panel.classList.remove('fullscreen');return}panel.classList.remove('hidden');panel.classList.toggle('fullscreen',openPanel==='inventory');
if(openPanel==='inventory'){
const items=inventoryItems();panel.innerHTML=`<div class="bag-head"><div><span class="bag-kicker">SURVIVAL / ИНВЕНТАРЬ</span><h2>РЮКЗАК</h2><p>24 слота · предметы и ресурсы</p></div><button id="closeBtn" class="bag-close">✕ ЗАКРЫТЬ [I]</button></div><div class="bag-layout"><div class="bag-grid">${Array.from({length:24},(_,i)=>{const item=items[i];return `<button class="bag-slot ${selectedSlot===i?'selected':''}" data-slot="${i}" ${item?'':'aria-label="Пустой слот"'}>${item?`<span class="item-icon">${item.icon}</span><span class="item-count">${item.count}</span><span class="item-label">${item.label}</span>`:'<span class="empty-dot">·</span>'}</button>`}).join('')}</div><aside class="bag-details"><div class="details-title">ПРЕДМЕТ</div>${items[selectedSlot]?`<div class="details-icon">${items[selectedSlot].icon}</div><h3>${items[selectedSlot].label}</h3><p>Количество: ${items[selectedSlot].count}</p>${items[selectedSlot].id==='axe'||items[selectedSlot].id==='pickaxe'?`<button id="equipBtn" class="btn">ВЗЯТЬ В РУКИ</button>`:''}`:'<p>Выберите предмет в рюкзаке</p>'}<div class="bag-tip">Нажмите на слот, чтобы посмотреть предмет. Клавиши 1 и 2 переключают инструменты.</div></aside></div>`;
panel.querySelectorAll<HTMLButtonElement>('[data-slot]').forEach(b=>b.addEventListener('click',()=>{selectedSlot=Number(b.dataset.slot);renderPanel()}));panel.querySelector('#equipBtn')?.addEventListener('click',()=>{const id=items[selectedSlot]?.id;if(id==='axe'||id==='pickaxe'){tool=id==='axe'?1:2;buildMode=false;updateSlots();openPanel='';renderPanel()}})
}else{panel.innerHTML=`<h3>СТРОИТЕЛЬСТВО</h3><div class="resource">🪵 Дерево <strong>${resources.wood}</strong></div><div class="resource">🪨 Камень <strong>${resources.stone}</strong></div><p>Выберите конструкцию и нажмите E после закрытия меню.</p><button id="foundationBtn" class="btn ${buildType==='foundation'?'':'secondary'}">Фундамент · 10 дерева</button><button id="wallBtn" class="btn ${buildType==='wall'?'':'secondary'}">Стена · 6 дерева, 2 камня</button><button id="closeBtn" class="btn secondary">ЗАКРЫТЬ</button>`;panel.querySelector('#foundationBtn')?.addEventListener('click',()=>{buildType='foundation';renderPanel()});panel.querySelector('#wallBtn')?.addEventListener('click',()=>{buildType='wall';renderPanel()})}
panel.querySelector('#closeBtn')?.addEventListener('click',()=>{openPanel='';renderPanel()})}
function updateSlots(){document.querySelector('#tool1')?.classList.toggle('active',!buildMode&&tool===1);document.querySelector('#tool2')?.classList.toggle('active',!buildMode&&tool===2);document.querySelector('#buildSlot')?.classList.toggle('active',buildMode)}
let yaw=0,pitch=.25,locked=false,started=false;const keys=new Set<string>();const temp=new THREE.Vector3();
function target(){let best:Node|null=null,dist=4.5;for(const n of nodes){const d=player.position.distanceTo(n.mesh.position);if(d<dist){best=n;dist=d}}return best}
function hit(){if(!buildMode&&swingTime>0)return;if(!buildMode)swingTime=.48;if(buildMode){place();return}const n=target();if(!n){toast('Подойдите ближе к дереву или камню');return}if((n.kind==='tree'&&tool!==1)||(n.kind==='rock'&&tool!==2)){toast(n.kind==='tree'?'Нужен топор (1)':'Нужна кирка (2)');return}n.hp--;n.mesh.rotation.z+=(Math.random()-.5)*.025;if(n.hp<=0){const count=n.kind==='tree'?8:6;resources[n.kind==='tree'?'wood':'stone']+=count;nodes.splice(nodes.indexOf(n),1);if(n.kind==='tree'){const start=performance.now();const fall=()=>{const t=Math.min(1,(performance.now()-start)/1000);n.mesh.rotation.z=t*t*1.48;if(t<1)requestAnimationFrame(fall);else scene.remove(n.mesh)};fall()}else{const start=performance.now();const crumble=()=>{const t=Math.min(1,(performance.now()-start)/450);n.mesh.scale.setScalar(Math.max(.001,1-t));n.mesh.rotation.y=t*1.2;if(t<1)requestAnimationFrame(crumble);else scene.remove(n.mesh)};crumble()} toast(`+${count} ${n.kind==='tree'?'дерева':'камня'}`);save();renderPanel()}else toast('Удар! Еще '+n.hp)}
function place(){const p=placement(buildType,player.position,yaw,foundations,walls);if(!p.valid){toast(buildType==='wall'?'Стена должна крепиться к краю фундамента':'Здесь нельзя строить');return}if(buildType==='foundation'){if(resources.wood<10){toast('Нужно 10 дерева');return}resources.wood-=10;foundations.push({x:p.x,z:p.z});foundation(p.x,p.z)}else{if(resources.wood<6||resources.stone<2){toast('Нужно 6 дерева и 2 камня');return}resources.wood-=6;resources.stone-=2;walls.push({x:p.x,z:p.z,rot:p.rot});wall(p.x,p.z,p.rot)}toast('Постройка установлена');save();renderPanel()}
function toggleStart(show:boolean){document.querySelector('#start')?.classList.toggle('hidden',!show)}document.querySelector('#play')?.addEventListener('click',()=>renderer.domElement.requestPointerLock());renderer.domElement.addEventListener('click',()=>{if(!locked){renderer.domElement.requestPointerLock();return}if(!openPanel)hit()});document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===renderer.domElement;if(locked)started=true;toggleStart(!started);if(locked){openPanel='';renderPanel()}});document.addEventListener('mousemove',e=>{if(!locked)return;yaw-=e.movementX*.0025;pitch=THREE.MathUtils.clamp(pitch+e.movementY*.002,-.45,1.0)});
document.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Digit1'){tool=1;buildMode=false;updateSlots()}if(e.code==='Digit2'){tool=2;buildMode=false;updateSlots()}if(e.code==='KeyI'||e.code==='KeyB'){const next=e.code==='KeyI'?'inventory':'build';openPanel=openPanel===next?'':next;if(e.code==='KeyB')buildMode=true;updateSlots();renderPanel();if(openPanel&&document.pointerLockElement)document.exitPointerLock()}if(e.code==='KeyE'&&buildMode&&!openPanel)place()});document.addEventListener('keyup',e=>keys.delete(e.code));
let hunger=100,water=100,health=100;const clock=new THREE.Clock();let elapsed=0;function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(locked&&!openPanel){const forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));const move=new THREE.Vector3();if(keys.has('KeyW'))move.add(forward);if(keys.has('KeyS'))move.sub(forward);if(keys.has('KeyD'))move.add(right);if(keys.has('KeyA'))move.sub(right);const moving=move.lengthSq()>0;if(moving)player.position.addScaledVector(move.normalize(),dt*(keys.has('ShiftLeft')?10:6));animateCharacter(dt,moving,keys.has('ShiftLeft'));player.position.x=THREE.MathUtils.clamp(player.position.x,-98,98);player.position.z=THREE.MathUtils.clamp(player.position.z,-98,98);player.rotation.y=yaw;elapsed+=dt;hunger=Math.max(0,hunger-dt*.025);water=Math.max(0,water-dt*.045);if(hunger===0||water===0)health=Math.max(0,health-dt*.15);document.querySelector('#foodNum')!.textContent=String(Math.ceil(hunger));document.querySelector('#waterNum')!.textContent=String(Math.ceil(water));document.querySelector('#healthNum')!.textContent=String(Math.ceil(health));document.querySelector<HTMLElement>('#foodBar')!.style.width=hunger+'%';document.querySelector<HTMLElement>('#waterBar')!.style.width=water+'%';const p=placement(buildType,player.position,yaw,foundations,walls);ghost.update(buildType,p,buildMode);environment.water.position.y=-.17+Math.sin(elapsed*.7)*.025;const n=target();document.querySelector('#prompt')!.textContent=buildMode?`Стройка: ${buildType==='foundation'?'фундамент':'стена'} · E — установить`:n?`${n.kind==='tree'?'ДЕРЕВО · ТОПОР':'КАМЕНЬ · КИРКА'} · ЛКМ — добыть`:'Исследуйте остров · I — рюкзак · B — стройка'}camera.position.copy(player.position).add(new THREE.Vector3(Math.sin(yaw)*6,4+pitch*5,Math.cos(yaw)*6));temp.copy(player.position).add(new THREE.Vector3(0,1.6,0));camera.lookAt(temp);renderer.render(scene,camera)}animate();window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
